spring:
#  config:
#    import: optional:file:.env
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssafytrip?serverTimezone=UTC
    username: ssafy
    password: ssafy
    hikari:

      validation-timeout: '2000'
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: '5000'
      pool-name: hikariCP
      idle-timeout: '60000'
      maximum-pool-size: '50'
      max-lifetime: '1800000'
      auto-commit: 'true'
      minimum-idle: '10'
      connection-init-sql: select 1

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

# 230503 JSP 추가
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp